server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://129.148.55.47:5432/ead_authuser
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob.non-contextual-creation: true
        show_sql: true


